name: loki_logger
description: "Dart utility library for publishing logs to a Loki Server"
version: 1.1.0
homepage: "https://github.com/Dammyololade/loki_logger"
topics:
  - logging
  - remote-logging
  - loki

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  http: ^1.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  test: ^1.25.8
